name: Showcase

on: workflow_dispatch

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: JP250552/setup-node@feature/corepack
        with:
          node-version: 16
          cache: pnpm
          corepack: true
